

unset EPICS_CA_ADDR_LIST
unset EPICS_CA_AUTO_ADDR_LIST


echo $EPICS_CA_ADDR_LIST
echo $EPICS_CA_AUTO_ADDR_LIST

export EPICS_CA_ADDR_LIST="$1"
export EPICS_CA_AUTO_ADDR_LIST="$1";


echo $EPICS_CA_ADDR_LIST
echo $EPICS_CA_AUTO_ADDR_LIST

caget WAVEGENTRIG:IocStats:SYS_CPU_LOAD


